name: Local Docker Build

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop running instance + cleanup
        # env:
        run: |
          echo 'Stopping running instance right now'
          docker-compose -p mmk down
          docker rmi mmk-app 

      - name: Load and Run App
        run: |
          docker-compose -p mmk up -d
          docker logs mmk-app-1
          echo 'All done! Have fun.'
